# Generated by Django 5.2.13 on 2026-04-26 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TPPClient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=64, unique=True)),
                ('client_secret_hash', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scopes', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('AUTHORIZED', 'Authorized'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='CREATED', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accounts', models.ManyToManyField(blank=True, related_name='consents', to='banking.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to=settings.AUTH_USER_MODEL)),
                ('tpp_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='open_banking.tppclient')),
            ],
        ),
        migrations.CreateModel(
            name='TPPAccessLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=255)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('status_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='open_banking.consent')),
                ('tpp_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_banking.tppclient')),
            ],
            options={
                'indexes': [models.Index(fields=['tpp_client', 'created_at'], name='open_bankin_tpp_cli_317b5c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['user', 'status'], name='open_bankin_user_id_d22550_idx'),
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['tpp_client', 'status'], name='open_bankin_tpp_cli_22eff9_idx'),
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['expires_at'], name='open_bankin_expires_86ab79_idx'),
        ),
    ]
