# Generated by Django 5.2.13 on 2026-04-26 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('masked_pan', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=16)),
                ('daily_limit_minor', models.BigIntegerField(default=10000000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='banking.account')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'status'], name='cards_card_account_9f6965_idx')],
            },
        ),
    ]
