# Generated by Django 5.2.13 on 2026-04-25 17:35

import apps.banking.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_number', models.CharField(default=apps.banking.models.generate_public_account_number, max_length=32, unique=True)),
                ('currency', models.CharField(choices=[('RUB', 'RUB')], default='RUB', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16)),
                ('balance_minor', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('INTERNAL_TRANSFER', 'Internal transfer'), ('P2P', 'P2P'), ('TPP_PAYMENT', 'TPP payment'), ('ADJUSTMENT', 'Adjustment')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=16)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('amount_minor', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to=settings.AUTH_USER_MODEL)),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_operations', to='banking.account')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_operations', to='banking.account')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.BigIntegerField()),
                ('balance_after_minor', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='banking.account')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='banking.operation')),
            ],
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['owner', 'status'], name='banking_acc_owner_i_05652e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['public_number'], name='banking_acc_public__1cc080_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['created_by', 'created_at'], name='banking_ope_created_cd61ed_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['status', 'created_at'], name='banking_ope_status_e19267_idx'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', None), _negated=True), fields=('created_by', 'idempotency_key'), name='uniq_operation_idempotency_per_user'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'created_at'], name='banking_led_account_12c535_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['operation'], name='banking_led_operati_9f81d5_idx'),
        ),
    ]
